package compression.improvingGrammars;

import compression.RuleProbType;
import compression.data.CachedDataset;
import compression.data.Dataset;
import compression.data.FolderBasedDataset;
import compression.grammar.*;
import compression.grammargenerator.AutoGeneratedGrammars;
import compression.grammargenerator.RandomGrammarExplorer;
import compression.parser.SRFParser;
import compression.util.MyMultimap;

import java.util.*;
import java.util.stream.Collectors;

import static compression.grammargenerator.AbstractGrammarExplorer.getBitsPerBase;


public class SimpleLocalSearch  {

    List<Rule> allPossibleRules;
    SecondaryStructureGrammar initialGrammar;
    int steps = 0;
    int maxAttempts;
    Dataset parsableDataset = new CachedDataset(new FolderBasedDataset("minimal-parsable"));
    Dataset smallDataset = new CachedDataset(new FolderBasedDataset("small-dataset"));
    Dataset fullDataset = new CachedDataset(new FolderBasedDataset("full-dataset"));
    List<List<Terminal<Character>>> parsableDatasetWords = new ArrayList<>(parsableDataset.getSize());


    //stolen from RandomGrammarExplorer because i don't need the entire class?
    // use 10 rules?
    int nNonterminals;
    private int[] usedRules;
    NonTerminal[] nonTerminals;


    public SecondaryStructureGrammar randomGrammar(final Random random, final int nRules) {
        while (true) {
            try {
                if (nRules < 1 || nRules > allPossibleRules.size()) {
                    throw new IllegalArgumentException("nRules must be between 1 and " + allPossibleRules.size());
                }
                MyMultimap<NonTerminal, Rule> rules = new MyMultimap<>();
                Arrays.fill(usedRules, 0);
                for (int i = 0; i < nRules; i++) {
                    int ruleIndex = random.nextInt(allPossibleRules.size());
                    usedRules[ruleIndex] = 1;
                    Rule rule = allPossibleRules.get(ruleIndex);
                    rules.put(rule.left, rule);
                }
                String name = "RandomGrammar_" + nNonterminals + "_" + nRules + "_" +
                        (Arrays.stream(usedRules).mapToObj(Integer::toString).collect(Collectors.joining("")));
                SecondaryStructureGrammar G = new SecondaryStructureGrammar(name, nonTerminals[nNonterminals - 1], rules);
//				System.out.println("G = " + G);
                return G;
            } catch (IllegalArgumentException e) {
                // ignore, created nonsense grammar
            }
        }
    }


    public static void main(String[] args) {
        SimpleLocalSearch simpleLocalSearch = new SimpleLocalSearch(args,100);


    }


    public SimpleLocalSearch(String[] args, int maxAttempts) {

        // allPossibleRules = AutoGeneratedGrammars.generateAllRules(Integer.parseInt(args[0]));
        allPossibleRules = AutoGeneratedGrammars.generateAllRules(100);
        initialGrammar = randomGrammar(new Random(), 10);
        this.maxAttempts = maxAttempts;
        randomSimpleStep(initialGrammar);

        for (RNAWithStructure rna : parsableDataset) {
            List<Terminal<Character>> terminals = rna.secondaryStructureAsTerminals();
            parsableDatasetWords.add(terminals);
        }
    }
    //searches for better next step
    public void walker(SecondaryStructureGrammar grammarToImprove) {
        int i = 0;
        RuleProbType model =  RuleProbType.SEMI_ADAPTIVE;
        while (i < maxAttempts) {
            //checks if it is a valid grammar exactly like in RandomGrammarExplorer (lvl1)
            boolean passedlvl1 = true;
            SecondaryStructureGrammar step = randomSimpleStep(grammarToImprove);
            SRFParser<Character> ssParser = new SRFParser<>(step);
            for (List<Terminal<Character>> word : parsableDatasetWords) {
                if (!ssParser.parsable(word)){
                    passedlvl1 = false;
                    break;
                }
            }
            //if it passes lvl 1, we now look if it is a better grammar on lvl2 / small data
            if (passedlvl1) {
                double avgBitsPerBaseSmallDatasetStep = getBitsPerBase(smallDataset, model, step, false);
                double avgBitsPerBaseSmallDatasetGrammarToImprove = getBitsPerBase(smallDataset, model, grammarToImprove, false);
                if(avgBitsPerBaseSmallDatasetStep < avgBitsPerBaseSmallDatasetGrammarToImprove){
                    //if the new Grammar step is better than the GrammarToImprove on level 2
                    double avgBitsPerBaseFullDatasetStep = getBitsPerBase(fullDataset, model, step, true);
                    double avgBitsPerBaseFullDatasetGrammarToImprove = getBitsPerBase(fullDataset, model, grammarToImprove, true);
                    if (avgBitsPerBaseFullDatasetStep < avgBitsPerBaseFullDatasetGrammarToImprove) {
                        walker(grammarToImprove);
                        steps ++;
                    }
                }
            }
            i++;
        }
        System.out.println("best grammar found: "+ grammarToImprove.toString());
        System.out.println(" ");
        System.out.println("It only took " + steps + ". Jay");
    }
    //
    public SecondaryStructureGrammar randomSimpleStep(SecondaryStructureGrammar grammarToImprove){
        Collection<Rule> allRules = grammarToImprove.getAllRules();
         Rule[] allRuleArray = allRules.toArray(new Rule[0]);
         int x = (int) (Math.random() * allRuleArray.length);
         int y = (int) (Math.random() * allPossibleRules.size());
         allRuleArray[x] = allPossibleRules.get(y);
         MyMultimap<NonTerminal, Rule> rules = new MyMultimap<>();
         for(Rule rule : allRuleArray){
             rules.put(rule.left, rule);
         }
         return new SecondaryStructureGrammar(grammarToImprove.name,grammarToImprove.startSymbol,rules);
    }

}
